name: Deployment
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/composite-actions/cached-deps
        with:
          caching: false
          cached_directory: 'node_modules'
      - name: Output information
        run: |
          echo "Cache used?  ${{ steps.cache-deps.outputs.cache-on }}"
          echo "Cache hit?  ${{ steps.cache-deps.outputs.cache-hit }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/composite-actions/cached-deps
        with:
          caching: true
          cached_directory: 'node_modules'
      - name: Output information
        run: |
          echo "Cache used?  ${{ steps.cache-deps.outputs.cache-on }}"
          echo "Cache hit?  ${{ steps.cache-deps.outputs.cache-hit }}"
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
     
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/composite-actions/cached-deps
        with:
          caching: false
          cached_directory: 'node_modules'
      - name: Output information
        run: |
          echo "Cache used?  ${{ steps.cache-deps.outputs.cache-on }}"
          echo "Cache hit?  ${{ steps.cache-deps.outputs.cache-hit }}"
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy-using-javascript:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site using Javascript action
        id: deploy
        uses: ./.github/actions/javascript-actions/s3-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: gha-custom-action-hosting
          bucket-region: us-east-2
          dist-folder: ./dist
      - name: Output information
        run: |
          echo "Live URL: ${{ steps.deploy.outputs.website-url }}"
  deploy-using-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site using Docker action
        id: deploy
        uses: ./.github/actions/docker-actions/s3-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: gha-custom-action-hosting
          bucket-region: us-east-2
          dist-folder: ./dist
      - name: Output information
        run: |
          echo "Live URL: ${{ steps.deploy.outputs.website-url }}"