name: Output secrets and vars
on:
  # push:
  #   branches:
  #     - main
  #     - dev
  workflow_dispatch:

env:
  MONGODB_DB_NAME: mongo-demo

jobs:
  sit:
    environment: sit
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    # environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set Env variable
        env:
          MY_WISH: YOUR_WISH 
        run: |
          echo "MY_WISH: ${{ env.MY_WISH }} "
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }} "
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }} "
          echo "PORT: ${{ env.PORT }} "
          echo "MY_WISH: ${{ env.MY_WISH }} "
          echo "From secrets and variables"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} "
  dev:
    environment: dev
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    # environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set Env variable
        env:
          MY_WISH: YOUR_WISH 
        run: |
          echo "MY_WISH: ${{ env.MY_WISH }} "
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }} "
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }} "
          echo "PORT: ${{ env.PORT }} "
          echo "MY_WISH: ${{ env.MY_WISH }} "
          echo "From secrets and variables"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} "

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, sit]
    steps:
      - name: Output information
        run: |
          echo "Running tests for ${{ matrix.environment }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }} "
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }} "
          echo "PORT: ${{ env.PORT }} "
          echo "MY_WISH: ${{ env.MY_WISH }} "
          echo "From secrets and variables"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} "
