name: hello workflow

on:
  workflow_dispatch:
  push:

jobs:
  Hello-job:
    runs-on: ubuntu-slim
    steps:
      - name: say hello
        run: echo "Hello"
# By default, workflows run in parallel  
  Good-Bye:
    runs-on: ubuntu-slim
    steps:
      - name: say goodbye
        run: echo "GoodBye!!!!"
      - name: Event name
        run:  |
          echo "Event name: ${{github.event_name}}"

  
  
