name: hello workflow

on:
  workflow_dispatch:
  push:

jobs:
  Hello:
    runs-on: ubuntu-slim
    steps:
      - name: say hello
        run: echo "Hello"
# By default, workflows run in parallel  
  Good-Bye:
    needs: Hello     # If you want sequential execution
    runs-on: ubuntu-slim
    steps:
      - name: say goodbye
        run: echo "GoodBye!!!!"
      - name: Event name
        run:  |
          echo "Event name: ${{github.event_name}}"
  Extras:
    if: github.ref == 'refs/heads/main'
    runs-on: Ubuntu-slim
    steps:
      - name: Runner OS
        shell: bash
        run:  |
          echo "This job is running on runner - $RUNNER_OS"
    

  
  
