name: Handle Issues

on: issues

# To trigger this workflow, create a issue in github repository

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"