name: Output secrets and vars
on:
  # push:
  #   branches:
  #     - main
  #     - dev
  workflow_dispatch:

env:
  MONGODB_DB_NAME: mongo-demo

jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    # environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Set Env variable
        env:
          MY_WISH: YOUR_WISH 
        run: |
          echo "MY_WISH: ${{ env.MY_WISH }} "
      # - name: Run server
      #   env:
      #     MY_WISH: YOUR_WISH # Just to demonstrate that env can be defined at step level too
      #   run: npm start & npx wait-on http://127.0.0.1:$PORT # $ENV is syntax for linux script, windows powershell $env:PORT
      # - name: Run tests
      #   run: npm test
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }} "
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }} "
          echo "PORT: ${{ env.PORT }} "
          echo "MY_WISH: ${{ env.MY_WISH }} "
          echo "From secrets and variables"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }} "
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }} "
          echo "PORT: ${{ env.PORT }} "
          echo "MY_WISH: ${{ env.MY_WISH }} "
          echo "From secrets and variables"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ vars.MONGODB_CLUSTER_ADDRESS }} "
          echo "MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} "
          echo "MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} "
